### ISSUE TITLE
不能执行，不能退出

### ISSUE THREAD

**Issue by willin** [ly-tools/ly#3]
ref: https://github.com/hexojs/hexo/issues/1985

应该主题问题，换一个主题就ok

**Comment by LingyuCoder** [comment]
我这边osx用你的package.json试了没问题，你把node_modules删了，npm cache clean之后重新npm install一下试试？看报错似乎是依赖安装不完全

**Comment by willin** [comment]
可行的前提：
1.不能使用cnpm只能通过npm去安装依赖
2.不能在主题目录下安装依赖，得到根目录下安装
3.不能跑webpack dev

**Comment by LingyuCoder** [comment]
只是使用主题不需要跑webpack dev，webpack是给开发主题的人用的，在主题目录下同理会安装开发主题需要的依赖，使用者不需要安装。至于cnpm我就不清楚了，看错误应该是c++库编译的问题，可能是node-gyp版本，可以尝试升级一下试试

**Comment by willin** [comment]
对，就是实时调试是不行的，只能手动编译，重启，看效果。

已经升到了 6.2.0 和 npm 3.9.3

**Comment by LingyuCoder** [comment]
实时调试是不行的，themes下的内容变更不会触发gitbook重新build，所以我之前调试都是在build下生成json拿出来再单独调试theme

**Comment by willin** [comment]
岁数大了，懒了。刚才我自己看了一下源码，重写了一个解决了

**Comment by willin** [comment]
看了一下几个你的其他项目，最明显的感触是代码太随性了。

**Comment by LingyuCoder** [comment]
这个项目是刚学react时候写的，现在react、react-router、webpack的dev server都有比较大的变动，也不好重新推倒再重做了。没明白代码随性啥意思，没懂，囧
